# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/DialogPapers.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogPapers(object):
    def setupUi(self, DialogPapers):
        DialogPapers.setObjectName("DialogPapers")
        DialogPapers.resize(700, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogPapers)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblPapers = QtWidgets.QTableWidget(DialogPapers)
        self.tblPapers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblPapers.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblPapers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblPapers.setObjectName("tblPapers")
        self.tblPapers.setColumnCount(0)
        self.tblPapers.setRowCount(0)
        self.verticalLayout.addWidget(self.tblPapers)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogPapers)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogPapers)
        self.buttonBox.rejected.connect(DialogPapers.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogPapers)

    def retranslateUi(self, DialogPapers):
        _translate = QtCore.QCoreApplication.translate
        DialogPapers.setWindowTitle(_translate("DialogPapers", "Joint papers"))
