# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/DialogExportText.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogExportText(object):
    def setupUi(self, DialogExportText):
        DialogExportText.setObjectName("DialogExportText")
        DialogExportText.resize(500, 800)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogExportText)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tvPublications = QtWidgets.QTreeView(DialogExportText)
        self.tvPublications.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvPublications.setHeaderHidden(True)
        self.tvPublications.setObjectName("tvPublications")
        self.verticalLayout.addWidget(self.tvPublications)
        self.groupBox = QtWidgets.QGroupBox(DialogExportText)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.sbMaxAuthors = QtWidgets.QSpinBox(self.groupBox)
        self.sbMaxAuthors.setMinimum(1)
        self.sbMaxAuthors.setMaximum(10000)
        self.sbMaxAuthors.setProperty("value", 100)
        self.sbMaxAuthors.setObjectName("sbMaxAuthors")
        self.horizontalLayout_2.addWidget(self.sbMaxAuthors)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbAbbrJournal = QtWidgets.QCheckBox(self.groupBox)
        self.cbAbbrJournal.setObjectName("cbAbbrJournal")
        self.horizontalLayout_3.addWidget(self.cbAbbrJournal)
        self.cbPeriodInAuthors = QtWidgets.QCheckBox(self.groupBox)
        self.cbPeriodInAuthors.setObjectName("cbPeriodInAuthors")
        self.horizontalLayout_3.addWidget(self.cbPeriodInAuthors)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbReferenceFormat = QtWidgets.QComboBox(DialogExportText)
        self.cbReferenceFormat.setObjectName("cbReferenceFormat")
        self.horizontalLayout.addWidget(self.cbReferenceFormat)
        self.btnEdit = QtWidgets.QPushButton(DialogExportText)
        self.btnEdit.setObjectName("btnEdit")
        self.horizontalLayout.addWidget(self.btnEdit)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tbReferences = QtWidgets.QPlainTextEdit(DialogExportText)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(12)
        self.tbReferences.setFont(font)
        self.tbReferences.setReadOnly(True)
        self.tbReferences.setObjectName("tbReferences")
        self.verticalLayout.addWidget(self.tbReferences)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogExportText)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(3, 2)

        self.retranslateUi(DialogExportText)
        self.buttonBox.rejected.connect(DialogExportText.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogExportText)

    def retranslateUi(self, DialogExportText):
        _translate = QtCore.QCoreApplication.translate
        DialogExportText.setWindowTitle(_translate("DialogExportText", "Export as text"))
        self.groupBox.setTitle(_translate("DialogExportText", "Formatting"))
        self.label.setText(_translate("DialogExportText", "Max authors:"))
        self.cbAbbrJournal.setText(_translate("DialogExportText", "Abbreviated journal name"))
        self.cbPeriodInAuthors.setText(_translate("DialogExportText", "Include periods in author list"))
        self.btnEdit.setText(_translate("DialogExportText", "Edit"))
