# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/EditReferenceFormat.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditReferenceFormat(object):
    def setupUi(self, EditReferenceFormat):
        EditReferenceFormat.setObjectName("EditReferenceFormat")
        EditReferenceFormat.resize(600, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditReferenceFormat)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(EditReferenceFormat)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tbName = QtWidgets.QLineEdit(EditReferenceFormat)
        self.tbName.setObjectName("tbName")
        self.verticalLayout.addWidget(self.tbName)
        self.tbCode = QtWidgets.QPlainTextEdit(EditReferenceFormat)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(12)
        self.tbCode.setFont(font)
        self.tbCode.setObjectName("tbCode")
        self.verticalLayout.addWidget(self.tbCode)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditReferenceFormat)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EditReferenceFormat)
        self.buttonBox.rejected.connect(EditReferenceFormat.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditReferenceFormat)

    def retranslateUi(self, EditReferenceFormat):
        _translate = QtCore.QCoreApplication.translate
        EditReferenceFormat.setWindowTitle(_translate("EditReferenceFormat", "Edit reference format"))
        self.label.setText(_translate("EditReferenceFormat", "Name:"))
