# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSettings(object):
    def setupUi(self, DialogSettings):
        DialogSettings.setObjectName("DialogSettings")
        DialogSettings.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DialogSettings)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tbName = QtWidgets.QLineEdit(DialogSettings)
        self.tbName.setObjectName("tbName")
        self.verticalLayout.addWidget(self.tbName)
        self.label_2 = QtWidgets.QLabel(DialogSettings)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tbScholar = QtWidgets.QLineEdit(DialogSettings)
        self.tbScholar.setObjectName("tbScholar")
        self.verticalLayout.addWidget(self.tbScholar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogSettings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogSettings)
        self.buttonBox.accepted.connect(DialogSettings.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogSettings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogSettings)

    def retranslateUi(self, DialogSettings):
        _translate = QtCore.QCoreApplication.translate
        DialogSettings.setWindowTitle(_translate("DialogSettings", "User settings"))
        self.label.setText(_translate("DialogSettings", "Full name:"))
        self.label_2.setText(_translate("DialogSettings", "Google Scholar profile:"))
